
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 17 16:36:32 CST 2012
//----------------------------------------------------

package codigointermedio;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 36;
  public static final int PAR2 = 32;
  public static final int NUMERO = 7;
  public static final int WHEN = 51;
  public static final int DISTINTO = 49;
  public static final int PAR1 = 31;
  public static final int FUNCTION = 12;
  public static final int POR = 26;
  public static final int PUT = 22;
  public static final int ENTERO = 6;
  public static final int OUT = 20;
  public static final int ARRAY = 3;
  public static final int FIN = 34;
  public static final int FOR = 17;
  public static final int INOUT = 21;
  public static final int AND = 47;
  public static final int NOT = 46;
  public static final int MENORIGUAL = 45;
  public static final int IS = 13;
  public static final int IGUAL = 10;
  public static final int TYPE = 30;
  public static final int OR = 48;
  public static final int IN = 18;
  public static final int GET = 23;
  public static final int BEGIN = 14;
  public static final int EXIT = 50;
  public static final int LOOP = 19;
  public static final int IF = 39;
  public static final int ID = 2;
  public static final int MAYORIGUAL = 44;
  public static final int OF = 9;
  public static final int BOOLEAN = 4;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int TRUE = 28;
  public static final int COMILLA = 37;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int NEWLINE = 38;
  public static final int MENOS = 25;
  public static final int MENOR = 43;
  public static final int MAYOR = 42;
  public static final int REAL = 8;
  public static final int ELSE = 40;
  public static final int PUNTO = 33;
  public static final int WHILE = 52;
  public static final int FLOAT = 5;
  public static final int THEN = 41;
  public static final int END = 15;
  public static final int FALSE = 29;
  public static final int ENTRE = 27;
  public static final int PROCEDURE = 11;
  public static final int MAS = 24;
}

